volumes:
  mssql_data:

networks:
  backend:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash /project/scripts/web_start.dev.sh"
    volumes:
      - .:/project
    networks:
      - backend
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=MarketPriceServiceDb;User Id=sa;Password=Strong!Passw0rd;TrustServerCertificate=True;Trusted_Connection=True;Integrated Security=False;"
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - backend
    environment:
      SA_PASSWORD: "Strong!Passw0rd"
    ports:
      - "1433:1433"
